name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          toolchain: nightly
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build w/ sqlite
      run: cargo build --verbose --features sqlx/sqlite
    - name: Build w/ postgres
      run: cargo build --verbose --features sqlx/postgres
